set_property PACKAGE_PIN V17 [get_ports {A0}]
set_property PACKAGE_PIN V16 [get_ports {A1}]
set_property PACKAGE_PIN U16 [get_ports {Y0}]
set_property PACKAGE_PIN E19 [get_ports {Y1}]
set_property PACKAGE_PIN U19 [get_ports {Y2}]
set_property PACKAGE_PIN V19 [get_ports {Y3}]
set_property IOSTANDARD LVCMOS33 [get_ports {A0 A1 Y0 Y1 Y2 Y3}]
